# Generated by Django 4.0 on 2022-09-06 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 17, 11, 58, 856822, tzinfo=utc))),
                ('updated', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 17, 11, 58, 856822, tzinfo=utc))),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
